#!/usr/bin/env bash

# Update system packages
sudo apt update -y
sudo apt upgrade -y

# Install Nginx
sudo apt install nginx -y

# Configure Nginx
sudo bash -c 'cat > /etc/nginx/sites-available/default << EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        return 200 "Hello World!";
    }
}
EOL'

# Restart Nginx
sudo service nginx restart
