#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

a=1
for a in {1..100}
do
	if ((a % 3 == 0 && a % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((a % 3 == 0))
	then
		echo "Fizz"
	elif ((a % 5 == 0))
	then
		echo "Buzz"
	else
		echo $a
	fi
	((a++))
done
