#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

min=0
hour=0

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	while [ $min -lt 60 ]
		do
			echo $min
			((min++))
		done
	((min = 0))
	((hour++))
done
